Documentation/create new readme
energinet-singularity/dlr-parser pull request #17
Opened 2022-01-31 13:59 UTC by stigsberg

**Description of your changes**

Category:

- [x] New Feature
- [ ] Bugfix
- [x] Documentation update

Checklist:

- [x] I have bumped all relevant version numbers
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have documented my changes if this is needed
- [x] I have described my changes in the "description of your changes" field
- [x] I have tested this change on a running cluster 
- [x] I have created/corrected automated tests related to the changes, if possible/necessary
- [x] I have checked that new and existing unit tests pass locally with my changes

2022-02-02 09:15 UTC, swedchef requested changes
Generally a very good update and documentation.

I could not check against kafka, but the "true"/"false" flag is not working and needs to be fixed. Furthermore, please check the logging level you are using, and be certain you are logging as expected (i marked the places where i think it should be something else).

2022-02-02 09:15 UTC, swedchef commented on app/dlr_limit_consumer.py
> +            log.debug(f"Failed to connect to kafka topic: {e}")
I would suggest using "warning" level - or "error", not debug.

2022-02-02 09:15 UTC, swedchef commented on app/dlr_limit_consumer.py
> +shape_data = os.environ.get('SHAPE_DATA', 'True')
This parameter will be stored as a string - if you need a bool, you will have to transform it!

2022-02-02 09:15 UTC, swedchef commented on app/dlr_limit_consumer.py
> +        if shape_data:
Tested it now - it does NOT work!

2022-02-02 09:49 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +        log.info('Input on IP is not set')
Well I aggre it exit the container but I prefer that this information is shown to the user regardless of log level otherwise you won't get any info why the container exit when spinning it up

2022-02-02 09:49 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +        log.info('Input on topic_name is not set')
Well I aggre it exit the container but I prefer that this information is shown to the user regardless of log level otherwise you won't get any info why the container exit when spinning it up

2022-02-02 09:49 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +        log.info('Input on file_name is not set')
Well I aggre it exit the container but I prefer that this information is shown to the user regardless of log level otherwise you won't get any info why the container exit when spinning it up

2022-02-02 09:49 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +            log.debug(f"Failed to connect to kafka topic: {e}")
I aggre, I will adjust it

2022-02-02 09:50 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +shape_data = os.environ.get('SHAPE_DATA', 'True')
In this case I do not need a bool, a string will do just fine with True/False statement

2022-02-02 13:09 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +                log.debug('I/O error')
Changed it to error

2022-02-02 13:12 UTC, stigsberg commented on app/dlr_limit_consumer.py
> +IP = os.environ.get('KAFKA_IP')
It's back to all caps "IP"

2022-02-02 13:26 UTC, swedchef approved these changes
The variable 'IP' does not follow the PEP8 style guide, but it is not breaking.
When handling an exception and force-exiting afterwards, I would prefer it was logged at "critical" level or perhaps using the included "exception" function.
Not breaking though - so approved!

2022-02-02 13:35 UTC, swedchef approved these changes

2022-02-04 13:45 UTC, vjsaini75 approved these changes

2022-02-07 07:43 UTC, merged